// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"be-arimbi/internal/features/auth"
	"be-arimbi/internal/features/detailitem"
	"be-arimbi/internal/features/item"
	"be-arimbi/internal/features/role"
	"be-arimbi/internal/features/user"
	"context"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitApp(db *gorm.DB, rdb *redis.Client, ctx context.Context) *AppContainer {
	authRepository := auth.NewAuthRepository(db)
	userRepository := user.NewUserRepository(db)
	roleRepository := role.NewRoleRepository(db)
	authService := auth.NewAuthService(authRepository, userRepository, roleRepository)
	authHandler := auth.NewAuthHandler(authService)
	roleService := role.NewRoleService(roleRepository)
	roleHandler := role.NewRoleHandler(roleService)
	userService := user.NewUserService(userRepository)
	userHandler := user.NewUserHandler(userService)
	itemRepository := item.NewItemRepository(db)
	itemService := item.NewItemService(itemRepository)
	itemHandler := item.NewItemHandler(itemService)
	detailItemRepository := detailitem.NewDetailItemRepository(db)
	detailItemService := detailitem.NewDetailItemService(detailItemRepository)
	detailItemHandler := detailitem.NewDetailItemHandler(detailItemService)
	appContainer := &AppContainer{
		AuthHandler:       authHandler,
		RoleHandler:       roleHandler,
		UserHandler:       userHandler,
		ItemHandler:       itemHandler,
		DetailItemHandler: detailItemHandler,
	}
	return appContainer
}

// wire.go:

var detailItemSet = wire.NewSet(detailitem.NewDetailItemRepository, detailitem.NewDetailItemService, detailitem.NewDetailItemHandler)

var itemSet = wire.NewSet(item.NewItemRepository, item.NewItemService, item.NewItemHandler)

var roleSet = wire.NewSet(role.NewRoleRepository, role.NewRoleService, role.NewRoleHandler)

var authSet = wire.NewSet(auth.NewAuthRepository, auth.NewAuthService, auth.NewAuthHandler)

var userSet = wire.NewSet(user.NewUserRepository, user.NewUserService, user.NewUserHandler)
